version: '3'

services:
  db_slave:
    build: db-slave
    restart: always
    environment:
      MYSQL_USER: ${SLAVE_MYSQL_USER}
      MYSQL_PASSWORD: ${SLAVE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SLAVE_MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${SLAVE_MYSQL_ROOT_PASSWORD}
    ports:
      - 10101:3306
    volumes:
      - ./db-slave/volume:/var/lib/mysql

  db_slave_1:
    build: db-slave-1
    restart: always
    environment:
      MYSQL_USER: ${SLAVE_MYSQL_USER}
      MYSQL_PASSWORD: ${SLAVE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SLAVE_MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${SLAVE_MYSQL_ROOT_PASSWORD}
    ports:
      - 10102:3306
    volumes:
      - ./db-slave-1/volume:/var/lib/mysql
