version: '3'

services:
  db:
    build: db
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 10100:3306
    volumes:
      - ./db/volume:/var/lib/mysql

  monolith:
    build: ./monolith
    env_file:
      - .env
    volumes:
      - ./monolith:/monolith
    ports:
      - 5000:5000
    depends_on:
      - db

  celery:
    build: ./monolith
    command: celery worker -A task.worker.celery --loglevel=info
    env_file:
      - .env
    volumes:
      - ./monolith:/monolith
    depends_on:
      - monolith
      - db

  tarantool:
    image: tarantool/tarantool:1.10.6
    volumes:
      - ./tarantool/volume:/var/lib/tarantool
      - ./tarantool/conf/init.lua:/opt/tarantool/init.lua
    ports:
      - 3301:3301

  tarantool-replicator:
    build: ./tarantool-replicator
    privileged: true
    depends_on:
      - db
      - tarantool

  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ./redis/volume:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/volume:/var/lib/rabbitmq
